version: "3"

services:

  nextcloud:
    container_name: nextcloud
    image: nextcloud
    restart: always
    networks:
      - local
    volumes:
      - "nextcloud:/var/www/html/"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=https"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.raspberrypi.local`)"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

volumes:
  nextcloud:
    name: nextcloud

networks:
  local:
    name: local
